services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    volumes:
      - ~/mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=estoque
      - MONGO_INITDB_ROOT_USERNAME=estoque
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"